// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    public partial class Achievement
    {
        public Achievement()
        {
            ProfileAchievements = new HashSet<ProfileAchievement>();
        }

        [Key]
        [Column("AchievementID")]
        public int AchievementId { get; set; }
        [StringLength(32)]
        public string Title { get; set; } = null!;
        [StringLength(128)]
        public string? Content { get; set; }
        public int Rank { get; set; }
        [StringLength(32)]
        public string Code { get; set; } = null!;

        [InverseProperty("Achievement")]
        public virtual ICollection<ProfileAchievement> ProfileAchievements { get; set; }
    }
}