// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Agree")]
    [Index("CommentId", Name = "IX_Agree_CommentID")]
    [Index("MessageId", Name = "IX_Agree_MessageID")]
    [Index("ProfileId", Name = "IX_Agree_ProfileID")]
    public partial class Agree
    {
        [Key]
        [Column("AgreeID")]
        public int AgreeId { get; set; }
        public DateTime UpdateTime { get; set; }
        [Column("CommentID")]
        public int? CommentId { get; set; }
        [Column("MessageID")]
        public int? MessageId { get; set; }
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;

        [ForeignKey("CommentId")]
        [InverseProperty("Agrees")]
        public virtual Comment? Comment { get; set; }
        [ForeignKey("MessageId")]
        [InverseProperty("Agrees")]
        public virtual Message? Message { get; set; }
        [ForeignKey("ProfileId")]
        [InverseProperty("Agrees")]
        public virtual Profile Profile { get; set; } = null!;
    }
}