// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("ArticleViewIp")]
    [Index("ViewIpsId", Name = "IX_ArticleViewIp_ViewIpsId")]
    public partial class ArticleViewIp
    {
        [Key]
        [Column("ArticlesArticleID")]
        public int ArticlesArticleId { get; set; }
        [Key]
        public int ViewIpsId { get; set; }

        [ForeignKey("ArticlesArticleId")]
        [InverseProperty("ArticleViewIps")]
        public virtual Article ArticlesArticle { get; set; } = null!;
        [ForeignKey("ViewIpsId")]
        [InverseProperty("ArticleViewIps")]
        public virtual ViewIp ViewIps { get; set; } = null!;
    }
}