// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Article")]
    [Index("ProfileId", Name = "IX_Article_ProfileID")]
    public partial class Article
    {
        public Article()
        {
            ArticleArticleTags = new HashSet<ArticleArticleTag>();
            ArticleViewIps = new HashSet<ArticleViewIp>();
            ArticleViewers = new HashSet<ArticleViewer>();
            Comments = new HashSet<Comment>();
            Involvings = new HashSet<Involving>();
        }

        [Key]
        [Column("ArticleID")]
        public int ArticleId { get; set; }
        [StringLength(50)]
        public string Title { get; set; } = null!;
        public string Content { get; set; } = null!;
        public DateTime UpdateTime { get; set; }
        public int Views { get; set; }
        public bool Block { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalCoins { get; set; }
        [Column(TypeName = "money")]
        public decimal MonthlyCoins { get; set; }
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;
        public DateTime CreateTime { get; set; }
        public int DailyView { get; set; }
        public string? ViewRecordJson { get; set; }

        [ForeignKey("ProfileId")]
        [InverseProperty("Articles")]
        public virtual Profile Profile { get; set; } = null!;
        [InverseProperty("ArticlesArticle")]
        public virtual ICollection<ArticleArticleTag> ArticleArticleTags { get; set; }
        [InverseProperty("ArticlesArticle")]
        public virtual ICollection<ArticleViewIp> ArticleViewIps { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<ArticleViewer> ArticleViewers { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<Comment> Comments { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<Involving> Involvings { get; set; }
    }
}