// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("BiddingOption")]
    [Index("VotingId", Name = "IX_BiddingOption_VotingID")]
    public partial class BiddingOption
    {
        public BiddingOption()
        {
            Votes = new HashSet<Vote>();
        }

        [Key]
        [Column("BiddingOptionID")]
        public int BiddingOptionId { get; set; }
        [Column("OwnerID")]
        public string? OwnerId { get; set; }
        [Column(TypeName = "money")]
        public decimal BiddingCoins { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalCoins { get; set; }
        public DateTime CreateTime { get; set; }
        [StringLength(10)]
        public string? Content { get; set; }
        [Column("VotingID")]
        public int VotingId { get; set; }

        [ForeignKey("VotingId")]
        [InverseProperty("BiddingOptions")]
        public virtual Voting Voting { get; set; } = null!;
        [InverseProperty("BiddingOption")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}