// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Episode")]
    [Index("NovelId", Name = "IX_Episode_NovelID")]
    public partial class Episode
    {
        public Episode()
        {
            Comments = new HashSet<Comment>();
            Votings = new HashSet<Voting>();
        }

        [Key]
        [Column("EpisodeID")]
        public int EpisodeId { get; set; }
        [StringLength(20)]
        public string Title { get; set; } = null!;
        [Column("OwnerID")]
        public string? OwnerId { get; set; }
        public string Content { get; set; } = null!;
        public DateTime UpdateTime { get; set; }
        public int Views { get; set; }
        public bool HasVoting { get; set; }
        public bool IsLast { get; set; }
        [Column("NovelID")]
        public int NovelId { get; set; }

        [ForeignKey("NovelId")]
        [InverseProperty("Episodes")]
        public virtual Novel Novel { get; set; } = null!;
        [InverseProperty("Episode")]
        public virtual ICollection<Comment> Comments { get; set; }
        [InverseProperty("Episode")]
        public virtual ICollection<Voting> Votings { get; set; }
    }
}