// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Feedback")]
    public partial class Feedback
    {
        public Feedback()
        {
            Comments = new HashSet<Comment>();
        }

        [Key]
        [Column("FeedbackID")]
        public int FeedbackId { get; set; }
        [StringLength(50)]
        public string Title { get; set; } = null!;
        [Column("OwnerID")]
        public string? OwnerId { get; set; }
        public string? OwnerName { get; set; }
        public string Content { get; set; } = null!;
        public DateTime UpdateTime { get; set; }
        public bool Block { get; set; }
        [Required]
        public bool? Accept { get; set; }

        [InverseProperty("Feedback")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}