// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Index("ProfileId", Name = "IX_Missions_ProfileID", IsUnique = true)]
    public partial class Mission
    {
        [Key]
        [Column("MissionsID")]
        public int MissionsId { get; set; }
        public bool WatchArticle { get; set; }
        public bool Vote { get; set; }
        public bool LeaveComment { get; set; }
        public bool ViewAnnouncement { get; set; }
        public bool ShareCreation { get; set; }
        public bool BeAgreed { get; set; }
        public bool CompleteOtherMissions { get; set; }
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;
        [Required]
        public bool? DailyLogin { get; set; }

        [ForeignKey("ProfileId")]
        [InverseProperty("Mission")]
        public virtual Profile Profile { get; set; } = null!;
    }
}