// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("NormalOption")]
    [Index("VotingId", Name = "IX_NormalOption_VotingID")]
    public partial class NormalOption
    {
        public NormalOption()
        {
            Votes = new HashSet<Vote>();
        }

        [Key]
        [Column("NormalOptionID")]
        public int NormalOptionId { get; set; }
        [Column("OwnerID")]
        public string? OwnerId { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalCoins { get; set; }
        [StringLength(20)]
        public string? Content { get; set; }
        [Column("VotingID")]
        public int VotingId { get; set; }

        [ForeignKey("VotingId")]
        [InverseProperty("NormalOptions")]
        public virtual Voting Voting { get; set; } = null!;
        [InverseProperty("NormalOption")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}