// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Index("ProfileId", Name = "IX_Notifications_ProfileID")]
    public partial class Notification
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool IsRead { get; set; }
        [StringLength(128)]
        public string? Url { get; set; }
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;

        [ForeignKey("ProfileId")]
        [InverseProperty("Notifications")]
        public virtual Profile Profile { get; set; } = null!;
    }
}