// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("NovelViewer")]
    [Index("NovelId", Name = "IX_NovelViewer_NovelID")]
    public partial class NovelViewer
    {
        [Key]
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;
        [Key]
        [Column("NovelID")]
        public int NovelId { get; set; }
        public int SeqNo { get; set; }
        public DateTime ViewDate { get; set; }

        [ForeignKey("NovelId")]
        [InverseProperty("NovelViewers")]
        public virtual Novel Novel { get; set; } = null!;
        [ForeignKey("ProfileId")]
        [InverseProperty("NovelViewers")]
        public virtual Profile Profile { get; set; } = null!;
    }
}