// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("NovelNovelTag")]
    [Index("NovelsNovelId", Name = "IX_NovelNovelTag_NovelsNovelID")]
    public partial class NovelNovelTag
    {
        [Key]
        public int NovelTagsTagId { get; set; }
        [Key]
        [Column("NovelsNovelID")]
        public int NovelsNovelId { get; set; }

        [ForeignKey("NovelTagsTagId")]
        [InverseProperty("NovelNovelTags")]
        public virtual NovelTag NovelTagsTag { get; set; } = null!;
        [ForeignKey("NovelsNovelId")]
        [InverseProperty("NovelNovelTags")]
        public virtual Novel NovelsNovel { get; set; } = null!;
    }
}