// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("NovelViewIp")]
    [Index("ViewIpsId", Name = "IX_NovelViewIp_ViewIpsId")]
    public partial class NovelViewIp
    {
        [Key]
        [Column("NovelsNovelID")]
        public int NovelsNovelId { get; set; }
        [Key]
        public int ViewIpsId { get; set; }

        [ForeignKey("NovelsNovelId")]
        [InverseProperty("NovelViewIps")]
        public virtual Novel NovelsNovel { get; set; } = null!;
        [ForeignKey("ViewIpsId")]
        [InverseProperty("NovelViewIps")]
        public virtual ViewIp ViewIps { get; set; } = null!;
    }
}