// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Payment")]
    public partial class Payment
    {
        [Key]
        [Column("PaymentID")]
        public int PaymentId { get; set; }
        public string? RtnMsg { get; set; }
        public string? TradeNo { get; set; }
        public int TradeAmt { get; set; }
        public string? PaymentDate { get; set; }
        public string? TradeDate { get; set; }
        public string? ReturnString { get; set; }
        [Column("InvolverID")]
        public string? InvolverId { get; set; }
        public string? RequestBody { get; set; }
        public string? MerchantTradeNo { get; set; }
        public int RtnCode { get; set; }
        public int SimulatePaid { get; set; }
    }
}