// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Profile")]
    public partial class Profile
    {
        public Profile()
        {
            Agrees = new HashSet<Agree>();
            ArticleViewers = new HashSet<ArticleViewer>();
            Articles = new HashSet<Article>();
            Comments = new HashSet<Comment>();
            FollowFollowers = new HashSet<Follow>();
            FollowProfiles = new HashSet<Follow>();
            InvolvingInvolvers = new HashSet<Involving>();
            InvolvingProfiles = new HashSet<Involving>();
            Messages = new HashSet<Message>();
            Notifications = new HashSet<Notification>();
            NovelViewers = new HashSet<NovelViewer>();
            Novels = new HashSet<Novel>();
            ProfileAchievements = new HashSet<ProfileAchievement>();
        }

        [Key]
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;
        [StringLength(256)]
        public string? Introduction { get; set; }
        [Column(TypeName = "money")]
        public decimal RealCoins { get; set; }
        [Column(TypeName = "money")]
        public decimal VirtualCoins { get; set; }
        [Column(TypeName = "money")]
        public decimal MonthlyCoins { get; set; }
        [StringLength(50)]
        public string UserName { get; set; } = null!;
        public DateTime EnrollmentDate { get; set; }
        public DateTime LastTimeLogin { get; set; }
        public bool Professional { get; set; }
        public bool Prime { get; set; }
        public bool Banned { get; set; }
        public int Views { get; set; }
        [Required]
        public bool? CanChangeUserName { get; set; }
        [StringLength(128)]
        public string? BannerImageUrl { get; set; }
        [StringLength(128)]
        public string? ImageUrl { get; set; }
        public int SeqNo { get; set; }
        [Column(TypeName = "money")]
        public decimal UsedCoins { get; set; }

        [InverseProperty("Profile")]
        public virtual Mission? Mission { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Agree> Agrees { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<ArticleViewer> ArticleViewers { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Article> Articles { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Comment> Comments { get; set; }
        [InverseProperty("Follower")]
        public virtual ICollection<Follow> FollowFollowers { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Follow> FollowProfiles { get; set; }
        [InverseProperty("Involver")]
        public virtual ICollection<Involving> InvolvingInvolvers { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Involving> InvolvingProfiles { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Message> Messages { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<NovelViewer> NovelViewers { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<Novel> Novels { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<ProfileAchievement> ProfileAchievements { get; set; }
    }
}