// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("ProfileAchievement")]
    [Index("AchievementId", Name = "IX_ProfileAchievement_AchievementID")]
    public partial class ProfileAchievement
    {
        [Key]
        [Column("ProfileID")]
        public string ProfileId { get; set; } = null!;
        [Key]
        [Column("AchievementID")]
        public int AchievementId { get; set; }
        public DateTime AchieveDate { get; set; }
        public int SeqNo { get; set; }

        [ForeignKey("AchievementId")]
        [InverseProperty("ProfileAchievements")]
        public virtual Achievement Achievement { get; set; } = null!;
        [ForeignKey("ProfileId")]
        [InverseProperty("ProfileAchievements")]
        public virtual Profile Profile { get; set; } = null!;
    }
}