// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("ProfitSharing")]
    public partial class ProfitSharing
    {
        [Key]
        [Column("ProfitSharingID")]
        public int ProfitSharingId { get; set; }
        [Column("InvolverID")]
        public string? InvolverId { get; set; }
        public string? CreditCard { get; set; }
        public int SharingValue { get; set; }
        public bool SharingDone { get; set; }
    }
}