// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    public partial class ViewIp
    {
        public ViewIp()
        {
            ArticleViewIps = new HashSet<ArticleViewIp>();
            NovelViewIps = new HashSet<NovelViewIp>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string Ip { get; set; } = null!;

        [InverseProperty("ViewIps")]
        public virtual ICollection<ArticleViewIp> ArticleViewIps { get; set; }
        [InverseProperty("ViewIps")]
        public virtual ICollection<NovelViewIp> NovelViewIps { get; set; }
    }
}