// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Vote")]
    [Index("BiddingOptionId", Name = "IX_Vote_BiddingOptionID")]
    [Index("NormalOptionId", Name = "IX_Vote_NormalOptionID")]
    public partial class Vote
    {
        [Key]
        [Column("VoteID")]
        public int VoteId { get; set; }
        [Column("OwnerID")]
        public string? OwnerId { get; set; }
        [Column(TypeName = "money")]
        public decimal Value { get; set; }
        [Column("BiddingOptionID")]
        public int? BiddingOptionId { get; set; }
        [Column("NormalOptionID")]
        public int? NormalOptionId { get; set; }

        [ForeignKey("BiddingOptionId")]
        [InverseProperty("Votes")]
        public virtual BiddingOption? BiddingOption { get; set; }
        [ForeignKey("NormalOptionId")]
        [InverseProperty("Votes")]
        public virtual NormalOption? NormalOption { get; set; }
    }
}