// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models.Database
{
    [Table("Voting")]
    [Index("EpisodeId", Name = "IX_Voting_EpisodeID")]
    public partial class Voting
    {
        public Voting()
        {
            BiddingOptions = new HashSet<BiddingOption>();
            NormalOptions = new HashSet<NormalOption>();
        }

        [Key]
        [Column("VotingID")]
        public int VotingId { get; set; }
        [Column("OwnerID")]
        public string? OwnerId { get; set; }
        [StringLength(20)]
        public string Title { get; set; } = null!;
        public int Policy { get; set; }
        public int Mode { get; set; }
        public int Limit { get; set; }
        public int Threshold { get; set; }
        public int? BiddingLowerLimit { get; set; }
        public int? NumberLimit { get; set; }
        public int? CoinLimit { get; set; }
        public bool End { get; set; }
        public int TotalNumber { get; set; }
        public int TotalCoins { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime? DeadLine { get; set; }
        [Column("EpisodeID")]
        public int EpisodeId { get; set; }

        [ForeignKey("EpisodeId")]
        [InverseProperty("Votings")]
        public virtual Episode Episode { get; set; } = null!;
        [InverseProperty("Voting")]
        public virtual ICollection<BiddingOption> BiddingOptions { get; set; }
        [InverseProperty("Voting")]
        public virtual ICollection<NormalOption> NormalOptions { get; set; }
    }
}